### ISSUE TITLE
Object pool thread safety?

### ISSUE THREAD

**Issue by resurtm** [yksz/go-design-patterns#1]
Hi @yksz!

https://github.com/yksz/go-design-patterns/blob/master/creation/object_pool.go

Is this code thread safe? For example:
```go
func (p *ObjectPool) ReturnObject(object *PooledObject) {
	fmt.Printf("Return: %s\n", object)
	p.idle.PushBack(object)
	p.remove(p.active, object)
}
```
Shouldn't both these list operations must be enclosed into `sync.RWMutex` lock for thread safety?

Cheers,
@resurtm

**Comment by yksz** [comment]
I think you're right.

It should be locked into ReturnObject() and BorrowObject().
I'm gonna fix these methods.

Thank you.

**Comment by resurtm** [comment]
@yksz Thank you for your repository! I'll take a look to other patterns too. Looks interesting. :+1:
